#!/usr/bin/env python3
"""Default configuration shared by all beehive mission nodes."""

import math


class MissionConfig:
    WORLD_FRAME = "odom"
    PCL_FRAME = "plantation"

    # Flight lifecycle
    FLIGHT_MODE = "GUIDED"
    FLIGHT_ALTITUDE = 3.0
    PRESTREAM_SEC = 30.0
    COMMAND_RETRY_SEC = 2.5
    LAND_RETRY_SEC = 5.0
    TAKEOFF_TIMEOUT_SEC = 35.0
    TAKEOFF_PROGRESS_CHECK_SEC = 8.0
    MIN_TAKEOFF_PROGRESS = 0.20
    HOME_REACHED_TOLERANCE = 0.8
    LAND_COMPLETE_ALTITUDE = 0.25
    POSE_TIMEOUT_SEC = 1.0
    MAP_TIMEOUT_SEC = 2.0
    STATE_TIMEOUT_SEC = 90.0

    # Stable hover detection
    HOVER_ALT_TOLERANCE = 0.25
    HOVER_SPEED_TOLERANCE = 0.20
    HOVER_STABLE_SEC = 1.5

    # Plantation exploration
    EXPLORE_STEP = 2.0
    CRAB_STEP = 1.5
    END_OF_ROW_DIST = 10.0
    END_OF_FARM_DIST = 20.0
    TREE_SEARCH_RADIUS = 18.0
    TREE_MIN_CONFIDENCE = 0.35
    VERIFY_DURATION_SEC = 1.5
    VERIFY_POSITION_TOLERANCE = 1.0

    # Orbit
    ORBIT_RADIUS = 3.0
    ORBIT_ALTITUDE = FLIGHT_ALTITUDE
    ORBIT_VELOCITY = 0.8
    ORBIT_DIRECTION = 1.0
    ORBIT_LOOKAHEAD_DISTANCE = 1.2
    ORBIT_RADIAL_GAIN = 0.35
    ORBIT_RADIUS_TOLERANCE = 0.45
    ORBIT_START_TOLERANCE = 0.65
    ORBIT_COMPLETION_MARGIN = math.radians(8.0)
    ORBIT_TIMEOUT_SEC = 75.0
    YAW_OFFSET = 0.0

    # Obstacle avoidance
    OBSTACLE_INFLUENCE_RADIUS = 3.0
    OBSTACLE_HARD_RADIUS = 1.2
    REPULSIVE_GAIN = 1.1
    VORTEX_GAIN = 0.55
    ATTRACTION_GAIN = 1.0
    MAX_TARGET_SHIFT = 1.5
    ACTIVE_TARGET_EXCLUSION_RADIUS = 0.8

    # Velocity controller
    KP_XY = 0.65
    KP_Z = 0.80
    KP_YAW = 1.0
    MAX_VELOCITY_XY = 1.0
    MAX_VELOCITY_Z = 0.80
    MAX_VELOCITY_YAW = 0.55
    MAX_ACCELERATION_XY = 0.8
    MAX_ACCELERATION_Z = 0.8
    GOAL_THRESHOLD_XY = 0.20
    GOAL_THRESHOLD_Z = 0.10
    TARGET_TIMEOUT_SEC = 0.75

    # PCL tree map
    PCL_TOPIC = "/perception/pcl/tracked_cylinders"
    PCL_MIN_SEEN_COUNT = 2
    PCL_MAX_MISSED_COUNT = 8
    PCL_MIN_CONFIDENCE = 0.25
    PCL_MIN_RADIUS = 0.08
    PCL_MAX_RADIUS = 1.20
    PCL_MIN_HEIGHT = 0.8
    PCL_MAX_HEIGHT = 20.0
    TREE_STALE_SEC = 8.0
    TREE_REJECT_HOLD_SEC = 20.0
    TREE_FALLBACK_MERGE_DISTANCE = 2.0

    # YOLO fallback
    YOLO_CONFIDENCE = 0.35
    YOLO_IOU = 0.45
    YOLO_MAX_DEPTH = 20.0
    YOLO_MIN_DEPTH = 0.25
    YOLO_DEVICE = "cpu"
    YOLO_TARGET_LABELS = ["palm", "palm_tree", "tree", "oil_palm"]
