- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/plantation_uav/gazebo/command/twist"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: "ROS_TO_GZ"

- ros_topic_name: "/imu"
  gz_topic_name: "/plantation_uav/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/zed2i/left/image_rect_color"
  gz_topic_name: "/plantation_uav/zed2i/left/image_rect_color"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/zed2i/left/camera_info"
  gz_topic_name: "/plantation_uav/zed2i/left/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/zed2i/right/image_rect_color"
  gz_topic_name: "/plantation_uav/zed2i/right/image_rect_color"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/zed2i/right/camera_info"
  gz_topic_name: "/plantation_uav/zed2i/right/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/zed2i/depth/depth_registered"
  gz_topic_name: "/plantation_uav/zed2i/depth/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/zed2i/depth/camera_info"
  gz_topic_name: "/plantation_uav/zed2i/depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/range"
  gz_topic_name: "/plantation_uav/range"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: "GZ_TO_ROS"
